uipdate

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,75 +3,63 @@ name: Deploy Frontend
 on:
   push:
     branches:
-      - main  # Se ejecuta solo cuando se hace push a la rama 'main'
+      - main # Se ejecuta solo cuando se hace push a la rama 'main'
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '18'
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: "18"
 
-    - name: Install dependencies
-      run: |
-        npm install
-
-    - name: Build the project
-      run: |
-        npm run build
-
-    - name: Set up SSH key
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.VALESERVER  }}
-
-    - name: Deploy the frontend
-      run: |
-        ssh -o StrictHostKeyChecking=no root@93.127.212.162 << 'EOF'
-          cd /home/valeriacorrea/frontend
-          
-          # Verificar si el directorio existe
-          if [ ! -d "/home/valeriacorrea/frontend" ]; then
-            echo "Error: El directorio no existe."
-            exit 1
-          fi
-          
-          # Hacer git pull para obtener los últimos cambios
-          git pull origin main
-          
-          # Instalar dependencias si es necesario
+      - name: Install dependencies
+        run: |
           npm install
-          
-          # Construir nuevamente el proyecto si es necesario
-          npm run build
-          
-          # Detener contenedores antiguos
-          docker-compose -f /home/valeriacorrea/docker-compose.yml down
-          
-          # Construir y ejecutar el contenedor frontend
-          docker-compose -f /home/valeriacorrea/docker-compose.yml up --build -d frontend
-          
-          # Verificar los contenedores
-          docker-compose -f /home/valeriacorrea/docker-compose.yml ps
-          
-          # Si usas Nginx o algún otro servicio
-          # sudo systemctl reload nginx
-        EOF
 
-    - name: Send Email Notification
-      uses: dawidd6/action-send-mail@v3
-      with:
-        server_address: 'smtp.gmail.com'
-        server_port: 587
-        username: ${{ secrets.GMAIL_USERNAME }}
-        password: ${{ secrets.GMAIL_PASSWORD }}
-        subject: 'Frontend Deployment Status'
-        to: 'marceloveron76@gmail.com'
-        from: 'marceloveron76@gmail.com'
-        body: 'El despliegue del frontend se ha completado exitosamente.'
+      - name: Build the project
+        run: |
+          npm run build
+
+      - name: Set up SSH key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.VALESERVER  }}
+
+      - name: Deploy the frontend
+        run: |
+          ssh -o StrictHostKeyChecking=no root@93.127.212.162 << 'EOF'
+            cd /home/valeriacorrea/frontend
+            
+            # Verificar si el directorio existe
+            if [ ! -d "/home/valeriacorrea/frontend" ]; then
+              echo "Error: El directorio no existe."
+              exit 1
+            fi
+            
+            # Hacer git pull para obtener los últimos cambios
+            git pull origin main
+            
+            # Instalar dependencias si es necesario
+            npm install
+            
+            # Construir nuevamente el proyecto si es necesario
+            npm run build
+            
+            # Detener contenedores antiguos
+            docker-compose -f /home/valeriacorrea/docker-compose.yml down
+            
+            # Construir y ejecutar el contenedor frontend
+            docker-compose -f /home/valeriacorrea/docker-compose.yml up --build -d frontend
+            
+            # Verificar los contenedores
+            docker-compose -f /home/valeriacorrea/docker-compose.yml ps
+            
+            # Si usas Nginx o algún otro servicio
+            # sudo systemctl reload nginx
+          EOF
